import asyncio
from hydrogram import Client, filters
from hydrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

# ==========================================
# 🎨 IMAGE GENERATION (Free API)
# ==========================================

@Client.on_message(filters.command(["draw", "imagine", "img"]))
async def draw_image(client, message):
    # 1. Check Input
    if len(message.command) < 2:
        return await message.reply(
            "🎨 **Image Generator**\n\n"
            "Usage: `/draw <prompt>`\n"
            "Example: `/draw a cyberpunk city with neon lights`"
        )

    # 2. Get Prompt
    prompt = message.text.split(None, 1)[1]
    
    # 3. Status Message
    msg = await message.reply("🎨 **Drawing...**\nकृपया प्रतीक्षा करें...")

    try:
        # 4. Construct API URL (Pollinations.ai is Free & No Key needed)
        # We replace spaces with %20 for URL encoding
        search_prompt = prompt.replace(" ", "%20")
        image_url = f"https://image.pollinations.ai/prompt/{search_prompt}"

        # 5. Send Photo
        await client.send_photo(
            chat_id=message.chat.id,
            photo=image_url,
            caption=f"✨ **Prompt:** `{prompt}`\n🤖 **Generated by:** @{client.me.username}",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("🗑 Delete", callback_data="close_data")]
            ])
        )
        await msg.delete()

    except Exception as e:
        await msg.edit(f"❌ **Error:** Failed to generate image.\n`{e}`")
